version: '2'

volumes:
        prometheus_data: {}
        grafana_data: {}

services:
    prometheus:
        image: prom/prometheus:0.18.0
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'
    node-exporter:
        image: prom/node-exporter
        ports:
            - '9100:9100'
    grafana:
        image: grafana/grafana:3.0.0-beta7
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=123
        depends_on:
            - prometheus
        ports:
            - "3001:3000"
        volumes:
            - grafana_data:/var/lib/grafana